<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Produit;

class ProduitsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Produit::insert([
            [
                'nomProd' => 'Samsung Galaxy Tab 4',
                'prix' => 45750,
                'stock' => 'En stock',
                'description' => 'La Samsung Galaxy Tab 4 est une tablette polyvalente qui offre une expérience utilisateur fluide, idéale pour le divertissement, le travail et l\'apprentissage.',
                'info' => 'Écran : 10.1 pouces TFT. - Processeur : Quad-Core 1.2 GHz. - RAM : 1.5 GB. - Stockage : 16 GB extensible via microSD. - Batterie : 6800 mAh. - Caméra : Arrière 3 MP, avant 1.3 MP.',
                'image' => 'images/produits/digital_01.jpg',
                'category_id' => 1,
            ],
            [
                'nomProd' => 'Motorola G4 Plus',
                'prix' => 44000,
                'stock' => 'En stock',
                'description' => 'Le Motorola G4 Plus est un smartphone performant et abordable, offrant une expérience utilisateur fluide avec un écran spacieux et une caméra de haute qualité. Parfait pour les utilisateurs à la recherche d\'un bon rapport qualité-prix.',
                'info' => 'Écran : 5.5 pouces Full HD. - Processeur : Octa-Core 1.5 GHz. - RAM : 2 GB. - Stockage : 16 GB, extensible via microSD. - Caméra : 16 MP arrière, 5 MP avant. - Batterie : 3000 mAh avec charge rapide.',
                'image' => 'images/produits/digital_02.jpg',
                'category_id' => 1,
            ],
            [
                'nomProd' => 'Yamaha TSX-B235',
                'prix' => 27500,
                'stock' => 'En stock',
                'description' => 'Le Yamaha TSX-B235 est un système audio de bureau qui combine élégance et performance. Profitez d\'un son riche et clair pour votre musique, vos podcasts et plus encore.',
                'info' => 'Puissance : 30W. - Connectivité : Bluetooth, USB, CD, radio FM/AM. - Fonctions : Alarme intégrée, chargeur de smartphone. - Design : Finition bois élégante.',
                'image' => 'images/produits/digital_03.jpg',
                'category_id' => 1,
            ],
            [
                'nomProd' => 'ASUS Vivobook Pro',
                'prix' => 95000,
                'stock' => 'En stock',
                'description' => 'Le ASUS Vivobook Pro est un ordinateur portable puissant conçu pour les professionnels et les créatifs. Son design fin et léger cache une puissance de traitement robuste et une qualité graphique exceptionnelle.',
                'info' => 'Processeur : Intel Core i7. - RAM : 16 GB. - Stockage : 512 GB SSD. - Carte graphique : NVIDIA GeForce GTX 1050. - Écran : 15.6 pouces Full HD.',
                'image' => 'images/produits/digital_04.jpg',
                'category_id' => 1,
            ],
            [
                'nomProd' => 'Samsung Galaxy Note Edge',
                'prix' => 65000,
                'stock' => 'En stock',
                'description' => 'Le Samsung Galaxy Note Edge est un smartphone innovant avec un écran courbé unique pour un accès rapide à vos notifications et applications.',
                'info' => 'Écran : 5.6 pouces Quad HD Super AMOLED. - Processeur : Quad-Core 2.7 GHz. - RAM : 3 GB. - Stockage : 32 GB, extensible via microSD. - Caméra : 16 MP arrière, 3.7 MP avant.',
                'image' => 'images/produits/digital_05.jpg',
                'category_id' => 1,
            ],
            [
                'nomProd' => 'Samsung Galaxy Camera',
                'prix' => 35690,
                'stock' => 'En stock',
                'description' => 'La Samsung Galaxy Camera combine la qualité d\'un appareil photo avec la connectivité d\'un smartphone. Capturez, éditez et partagez vos photos en un instant.',
                'info' => 'Capteur : 16 MP. - Zoom optique : 21x. - Écran : 4.8 pouces HD. - Système d\'exploitation : Android. - Connectivité : Wi-Fi, 4G.',
                'image' => 'images/produits/digital_06.jpg',
                'category_id' => 1,
            ],
            [
                'nomProd' => 'Samsung Galaxy Gear 360',
                'prix' => 65800,
                'stock' => 'En stock',
                'description' => 'Capturez vos moments préférés en 360 degrés avec la Samsung Galaxy Gear 360. Parfait pour les aventures et les souvenirs inoubliables, cet appareil compact vous permet de créer des vidéos immersives.',
                'info' => 'Résolution vidéo : 4K. - Capteur : Dual CMOS 8.4 MP. - Autonomie : Jusqu\'à 2 heures. - Connectivité : Bluetooth, Wi-Fi. - Compatibilité : Android et iOS.',
                'image' => 'images/produits/digital_07.jpg',
                'category_id' => 1,
            ],
            [
                'nomProd' => 'Sony Bravia XBR',
                'prix' => 105000,
                'stock' => 'En stock',
                'description' => 'La Sony Bravia XBR est une télévision de pointe offrant une qualité d\'image exceptionnelle et des fonctionnalités intelligentes pour une expérience de divertissement ultime.',
                'info' => 'Résolution : 4K Ultra HD. - Taille d\'écran : Disponible de 55\" à 85\". - Technologie d\'affichage : OLED pour des couleurs vives et des noirs profonds. - Smart TV : Compatible avec Netflix, Disney+, et plus. - Audio : Dolby Atmos pour un son immersif.',
                'image' => 'images/produits/digital_08.jpg',
                'category_id' => 1,
            ],
            [
                'nomProd' => 'Panasonic 39 Inch LED HD',
                'prix' => 85000,
                'stock' => 'En stock',
                'description' => 'La Panasonic 39 pouces LED HD est une télévision compacte offrant une qualité d\'image nette et claire, idéale pour les espaces plus petits.',
                'info' => 'Résolution : Full HD 1080p. - Taille d\'écran : 39 pouces. - Connectivité : HDMI, USB. - Technologie d\'affichage : LED. - Audio : Haut-parleurs intégrés avec technologie de son surround.',
                'image' => 'images/produits/digital_09.jpg',
                'category_id' => 1,
            ],
            [
                'nomProd' => 'Microsoft Xbox One Controller',
                'prix' => 15000,
                'stock' => 'En stock',
                'description' => 'La manette Xbox One de Microsoft offre un contrôle précis et un confort exceptionnel pour une expérience de jeu optimale. Compatible avec la console Xbox One et les PC Windows, elle est idéale pour les sessions de jeu prolongées.',
                'info' => 'Connectivité : Sans fil Bluetooth. - Compatibilité : Xbox One, PC Windows. - Autonomie : Jusqu\'à 30 heures avec des piles AA. - Ergonomie : Poignées texturées pour une meilleure prise en main. - Fonctions : Boutons analogiques et déclencheurs réactifs.',
                'image' => 'images/produits/digital_10.jpg',
                'category_id' => 1,
            ],
            [
                'nomProd' => 'Apple Watch Series 1',
                'prix' => 11000,
                'stock' => 'En stock',
                'description' => 'L\'Apple Watch Series 1 vous aide à rester connecté(e) et actif(ve). Suivez vos activités, recevez des notifications et utilisez vos applications préférées directement depuis votre poignet.',
                'info' => 'Écran : OLED Retina. - Processeur : S1P dual-core. - Résistance à l\'eau : Résistant aux éclaboussures. - Capteurs : Cardiofréquencemètre, accéléromètre, gyroscope. - Autonomie : Jusqu\'à 18 heures.',
                'image' => 'images/produits/digital_11.jpg',
                'category_id' => 1,
            ],
            [
                'nomProd' => 'VR G04BS sans fil Bluetooth VR Casque',
                'prix' => 76900,
                'stock' => 'En stock',
                'description' => 'Le casque VR G04BS offre une expérience de réalité virtuelle immersive sans fil, compatible avec une large gamme de smartphones.',
                'info' => 'Affichage : Lentilles ajustables. - Connectivité : Bluetooth. - Compatibilité : iOS et Android. - Ergonomie : Bandeau ajustable pour un confort optimal. - Autonomie : Jusqu\'à 3 heures d\'utilisation continue.',
                'image' => 'images/produits/digital_12.jpg',
                'category_id' => 1,
            ],
            [
                'nomProd' => 'Beats STUDIO 2.0',
                'prix' => 10500,
                'stock' => 'En stock',
                'description' => 'Les Beats Studio 2.0 sont des casques circum-auriculaires offrant une qualité sonore exceptionnelle et une réduction de bruit active. Conçus pour les audiophiles, ils vous permettent de profiter de votre musique avec une clarté et une profondeur incroyable.',
                'info' => 'Type : Circum-auriculaires. - Connectivité : Bluetooth. - Autonomie : Jusqu\'à 20 heures. - Réduction de bruit : Active. - Qualité sonore : Signature sonore Beats avec basses puissantes.',
                'image' => 'images/produits/digital_13.jpg',
                'category_id' => 1,
            ],
            [
                'nomProd' => 'Ultrabook Acer Aspire S7',
                'prix' => 100000,
                'stock' => 'En stock',
                'description' => 'L\'Acer Aspire S7 est un ultrabook élégant et puissant, parfait pour les professionnels en déplacement. Son design fin et léger cache une puissance de traitement impressionnante.',
                'info' => 'Processeur : Intel Core i7. - RAM : 8 GB. - Stockage : 256 GB SSD. - Écran : 13.3 pouces Full HD tactile. - Autonomie : Jusqu\'à 8 heures.',
                'image' => 'images/produits/digital_14.jpg',
                'category_id' => 1,
            ],
            [
                'nomProd' => 'Ninebot mini pro',
                'prix' => 75000,
                'stock' => 'En stock',
                'description' => 'Le Ninebot mini pro est un moyen de transport personnel intelligent et élégant, parfait pour vos déplacements quotidiens. Sa conception compacte et légère vous permet de l\'emporter partout avec vous.',
                'info' => 'Vitesse maximale : 18 km/h. - Autonomie : Jusqu\'à 30 km. - Poids : 12.8 kg. - Capacité de charge : Jusqu\'à 100 kg. - Caractéristiques : Pneu anti-dérapant, connectivité Bluetooth, commande via application mobile.',
                'image' => 'images/produits/digital_15.jpg',
                'category_id' => 1,
            ],
            [
                'nomProd' => 'Sony Smart Bluetooth Speaker',
                'prix' => 25000,
                'stock' => 'En stock',
                'description' => 'Le haut-parleur Bluetooth intelligent de Sony offre un son de haute qualité et des fonctionnalités intelligentes, parfait pour écouter de la musique ou répondre à des appels mains libres.',
                'info' => 'Puissance : 10W. - Connectivité : Bluetooth, NFC. - Autonomie : Jusqu\'à 12 heures. - Fonctions : Commandes vocales, assistant virtuel intégré. - Design : Compact et portable.',
                'image' => 'images/produits/digital_16.jpg',
                'category_id' => 1,
            ],
            [
                'nomProd' => 'Wireless Audio 360 R6 Portable',
                'prix' => 45000,
                'stock' => 'En stock',
                'description' => 'Le Wireless Audio 360 R6 de Samsung offre un son omnidirectionnel pour une expérience audio immersive, où que vous soyez.',
                'info' => 'Puissance : 30W. - Connectivité : Wi-Fi, Bluetooth. - Autonomie : Jusqu\'à 6 heures. - Design : Portable avec poignée intégrée. - Compatibilité : Application Samsung Multiroom.',
                'image' => 'images/produits/digital_17.jpg',
                'category_id' => 1,
            ],
            [
                'nomProd' => 'Microsoft Xbox One Lunar White Special Edition',
                'prix' => 11500,
                'stock' => 'En stock',
                'description' => 'La manette Microsoft Xbox One Lunar White Special Edition combine un design élégant avec des fonctionnalités avancées pour une expérience de jeu améliorée. Sa finition blanche et ses poignées texturées dorées offrent un confort et un style uniques.',
                'info' => 'Connectivité : Sans fil Bluetooth. - Compatibilité : Xbox One, PC Windows. - Autonomie : Jusqu\'à 30 heures avec des piles AA. - Ergonomie : Poignées texturées dorées pour un meilleur confort. - Fonctions : Retour haptique et gâchettes réactives.',
                'image' => 'images/produits/digital_18.jpg',
                'category_id' => 1,
            ],
            [
                'nomProd' => 'Dell UltraSharp U-14H',
                'prix' => 11000,
                'stock' => 'En stock',
                'description' => 'Le Dell UltraSharp U-14H est un moniteur professionnel offrant une qualité d\'image exceptionnelle avec une résolution élevée et une précision des couleurs inégalée. Idéal pour les créatifs et les professionnels exigeants, ce moniteur assure une expérience',
                'info' => 'Résolution : 4K UHD (3840x2160). - Taille d\'écran : 27 pouces. - Technologie d\'affichage : IPS pour des angles de vision larges et des couleurs vives. - Connectivité : HDMI, DisplayPort, USB-C. - Fonctions : Hub USB intégré, réglage en hauteur, pivot.',
                'image' => 'images/produits/digital_19.jpg',
                'category_id' => 1,
            ],
            [
                'nomProd' => 'Samsung UHD KS9500',
                'prix' => 215000,
                'stock' => 'En stock',
                'description' => 'La Samsung UHD KS9500 est une télévision courbée offrant une expérience visuelle immersive avec une résolution 4K et des couleurs éclatantes.',
                'info' => 'Résolution : 4K Ultra HD. - Taille d\'écran : Disponible de 55\" à 65\". - Technologie d\'affichage : Quantum Dot pour des couleurs riches et précises. - Smart TV : Interface intuitive et accès à de nombreuses applications. - Audio : Dolby Digital Plus.',
                'image' => 'images/produits/digital_20.jpg',
                'category_id' => 1,
            ],
            [
                'nomProd' => 'Samsung Gear 360 PNG',
                'prix' => 105000,
                'stock' => 'En stock',
                'description' => 'La Samsung Gear 360 PNG est une caméra compacte qui vous permet de capturer des photos et vidéos en 360 degrés, idéale pour les aventures et les événements.',
                'info' => 'Résolution vidéo : 4K. - Capteur : Dual CMOS 8.4 MP. - Autonomie : Jusqu\'à 2 heures. - Connectivité : Bluetooth, Wi-Fi. - Compatibilité : Android et iOS.',
                'image' => 'images/produits/digital_21.jpg',
                'category_id' => 1,
            ],
            [
                'nomProd' => 'Samsung Gear VR 2 Oculus',
                'prix' => 125000,
                'stock' => 'En stock',
                'description' => 'Le Samsung Gear VR 2, en partenariat avec Oculus, offre une expérience de réalité virtuelle avancée avec un large éventail de contenus immersifs.',
                'info' => 'Affichage : Lentilles avec champ de vision de 101°. - Connectivité : USB Type-C. - Compatibilité : Smartphones Samsung Galaxy. - Ergonomie : Bandeau ajustable pour un confort prolongé. - Contenu : Accès à des jeux, vidéos et applications VR.',
                'image' => 'images/produits/digital_22.jpg',
                'category_id' => 1,
            ],
            [
                'nomProd' => 'Montre Homme bracelet en cuir isolé',
                'prix' => 7500,
                'stock' => 'En stock',
                'description' => 'Cette montre pour homme avec bracelet en cuir isolé allie élégance et fonctionnalité. Son design classique et raffiné en fait un accessoire parfait pour toutes les occasions, que ce soit pour le travail ou les sorties décontractées.',
                'info' => 'Matériau du bracelet : Cuir véritable. - Mouvement : Quartz. - Résistance à l\'eau : 3 ATM (résistant aux éclaboussures). - Fonctions : Affichage de la date, chronomètre. - Diamètre du boîtier : 42 mm.',
                'image' => 'images/produits/fashion_01.jpg',
                'category_id' => 2,
            ],
            [
                'nomProd' => 'Porte-documents en cuir véritable',
                'prix' => 8000,
                'stock' => 'En stock',
                'description' => 'Ce porte-documents en cuir véritable est un choix idéal pour les professionnels. Avec ses multiples compartiments et son design sophistiqué, il vous permet de transporter vos documents et appareils électroniques en toute sécurité et avec style.',
                'info' => 'Matériau : Cuir véritable. - Dimensions : 40 cm x 30 cm x 10 cm. - Compartiments : Espace pour ordinateur portable, poches pour stylos, cartes et téléphone. - Fermeture : Fermeture éclair robuste. - Poignées : Poignées renforcées et bandoulière amovible.',
                'image' => 'images/produits/fashion_02.jpg',
                'category_id' => 2,
            ],
            [
                'nomProd' => 'Short en jean déchiré à taille',
                'prix' => 3500,
                'stock' => 'En stock',
                'description' => 'Ce short en jean déchiré à taille haute est parfait pour un look estival décontracté. Confortable et tendance, il peut être assorti à une variété de tops pour un style chic et casual.',
                'info' => 'Matériau : Denim 100% coton. - Taille : Haute. - Détails : Effet déchiré et usé. - Fermeture : Bouton et fermeture éclair. - Coupe : Regular fit.',
                'image' => 'images/produits/fashion_03.jpg',
                'category_id' => 2,
            ],
            [
                'nomProd' => 'Montre intelligente Golden Spike KW18',
                'prix' => 6000,
                'stock' => 'En stock',
                'description' => 'La montre intelligente Golden Spike KW18 combine style et technologie avancée. Idéale pour ceux qui cherchent à rester connectés et suivre leur santé, cette montre offre une multitude de fonctionnalités utiles.',
                'info' => 'Écran : 1.3 pouces TFT. - Connectivité : Bluetooth 4.0. - Fonctions : Moniteur de fréquence cardiaque, notifications de messages/appels, suivi des activités, surveillance du sommeil - Autonomie : Jusqu\'à 48 heures. - Compatibilité : iOS et Android.',
                'image' => 'images/produits/fashion_04.jpg',
                'category_id' => 2,
            ],
            [
                'nomProd' => 'Basket Homme Puma Roma SF Ferrari',
                'prix' => 7500,
                'stock' => 'En stock',
                'description' => 'Les baskets Puma Roma Sf Ferrari pour homme sont le parfait mélange de sportivité et d\'élégance. Inspirées par l\'univers Ferrari, elles offrent un confort optimal et un style inimitable.',
                'info' => 'Matériau : Cuir synthétique. - Semelle : Caoutchouc antidérapant. - Doublure : Textile respirant. - Détails : Logo Ferrari et Puma. - Fermeture : Lacets.',
                'image' => 'images/produits/fashion_05.jpg',
                'category_id' => 2,
            ],
            [
                'nomProd' => 'Cravate Homme en polyester',
                'prix' => 5000,
                'stock' => 'En stock',
                'description' => 'Cette cravate pour homme en polyester est un accessoire essentiel pour toute garde-robe professionnelle. Avec son design classique et sa texture lisse, elle ajoute une touche d\'élégance à n\'importe quelle tenue.',
                'info' => 'Matériau : Polyester. - Longueur : 150 cm. - Largeur : 8 cm. - Couleur : Disponible en plusieurs couleurs. - Entretien : Lavage à sec recommandé.',
                'image' => 'images/produits/fashion_06.jpg',
                'category_id' => 2,
            ],
            [
                'nomProd' => 'T-shirt Regular-Fit en lin mélangé',
                'prix' => 3500,
                'stock' => 'En stock',
                'description' => 'Ce t-shirt regular-fit en lin mélangé est parfait pour une tenue décontractée et confortable. Léger et respirant, il est idéal pour les journées chaudes.',
                'info' => 'Matériau : 55% lin, 45% coton. - Coupe : Regular fit. - Col : Rond. - Détails : Manches courtes. - Entretien : Lavable en machine.',
                'image' => 'images/produits/fashion_07.jpg',
                'category_id' => 2,
            ],
            [
                'nomProd' => 'Sac de voyage vintage - toile & cuir',
                'prix' => 8500,
                'stock' => 'En stock',
                'description' => 'Ce sac de voyage vintage en toile et cuir est à la fois robuste et élégant. Parfait pour les escapades de week-end, il offre suffisamment d\'espace pour tous vos essentiels.',
                'info' => 'Matériau : Toile durable et cuir véritable. - Dimensions : 55 cm x 30 cm x 25 cm. - Compartiments : Grand compartiment principal, poches intérieures et extérieures. - Fermeture : Fermeture éclair et boucles en cuir. - Poignées : Poignées en cuir et bandoulière réglable.',
                'image' => 'images/produits/fashion_08.jpg',
                'category_id' => 2,
            ],
            [
                'nomProd' => 'Veste Timberland 100% coton',
                'prix' => 6500,
                'stock' => 'En stock',
                'description' => 'La veste Timberland en 100% coton est un incontournable pour les amateurs de plein air. Elle offre confort et protection tout en arborant un style classique et intemporel.',
                'info' => 'Matériau : 100% coton. - Doublure : Partiellement doublée pour plus de confort. - Poches : Poches poitrine et latérales. - Fermeture : Fermeture éclair et boutons. - Couleur : Disponible en plusieurs couleurs.',
                'image' => 'images/produits/fashion_09.jpg',
                'category_id' => 2,
            ],
            [
                'nomProd' => 'Bottes de travail Kochmann',
                'prix' => 7000,
                'stock' => 'En stock',
                'description' => 'Les bottes de travail Kochmann sont conçues pour offrir une protection et un confort optimal sur le lieu de travail. Robustes et durables, elles sont idéales pour les environnements exigeants.',
                'info' => 'Matériau : Cuir résistant. - Semelle : Caoutchouc antidérapant. - Doublure : Textile respirant. - Renforcement : Embout de protection en acier. - Fermeture : Lacets robustes.',
                'image' => 'images/produits/fashion_10.jpg',
                'category_id' => 2,
            ],
            [
                'nomProd' => 'Table d\'appoint moderne avec étagère',
                'prix' => 115000,
                'stock' => 'En stock',
                'description' => 'Cette table d\'appoint moderne avec étagère est idéale pour ajouter une touche de sophistication à n\'importe quelle pièce. Sa conception pratique avec une étagère intégrée offre un espace de rangement supplémentaire pour vos livres, magazines ou décorations.',
                'info' => 'Matériau : MDF et métal. - Dimensions : 45 cm x 45 cm x 50 cm. - Couleur : Disponible en plusieurs finitions (blanc, noir, chêne). - Poids : 7 kg. - Assemblage : Facile à assembler, outils inclus.',
                'image' => 'images/produits/furniture_01.jpg',
                'category_id' => 3,
            ],
            [
                'nomProd' => 'Lampe de table pour salon en noir',
                'prix' => 75000,
                'stock' => 'En stock',
                'description' => 'Ajoutez une touche d\'élégance à votre salon avec cette lampe de table noire. Son design épuré et moderne s\'intègre parfaitement dans tout type de décor, offrant une lumière douce et agréable.',
                'info' => 'Matériau : Métal et tissu. - Dimensions : Hauteur 50 cm, diamètre 20 cm. - Type d\'ampoule : E27 (non incluse). - Couleur : Noir mat. - Interrupteur : Interrupteur à bascule sur le cordon.',
                'image' => 'images/produits/furniture_02.jpg',
                'category_id' => 3,
            ],
            [
                'nomProd' => 'Bibliothèque circulaire noir et marron Santa Monica',
                'prix' => 120000,
                'stock' => 'En stock',
                'description' => 'La bibliothèque circulaire Santa Monica allie design unique et fonctionnalité. Avec ses étagères ouvertes, elle permet de mettre en valeur vos livres et objets de décoration tout en ajoutant une touche contemporaine à votre espace.',
                'info' => 'Matériau : Bois MDF et métal. - Dimensions : Diamètre 120 cm, profondeur 30 cm. - Couleur : Noir et marron. - Poids : 30 kg. - Assemblage : Nécessite un assemblage, instructions incluses.',
                'image' => 'images/produits/furniture_03.jpg',
                'category_id' => 3,
            ],
            [
                'nomProd' => 'Chaise contemporaine en tissu/cuir/chêne',
                'prix' => 44000,
                'stock' => 'En stock',
                'description' => 'Cette chaise contemporaine en tissu, cuir et chêne est le complément parfait pour votre salle à manger ou votre bureau. Elle offre un confort exceptionnel grâce à son rembourrage de haute qualité et son design ergonomique.',
                'info' => 'Matériau : Tissu/cuir et bois de chêne. - Dimensions : Hauteur 85 cm, largeur 45 cm, profondeur 55 cm. - Couleur : Disponible en plusieurs combinaisons de couleurs. - Poids : 6 kg. - Capacité de charge : 120 kg.',
                'image' => 'images/produits/furniture_04.jpg',
                'category_id' => 3,
            ],
            [
                'nomProd' => 'Canapé-lit gris Nalpha',
                'prix' => 115000,
                'stock' => 'En stock',
                'description' => 'Le canapé-lit Nalpha gris est une solution pratique et élégante pour les petits espaces. Son design moderne et son mécanisme de transformation facile en font un meuble indispensable pour votre salon ou chambre d\'amis.',
                'info' => 'Matériau : Tissu et cadre en métal. - Dimensions : Canapé : 200 cm x 90 cm x 85 cm. ; Lit : 200 cm x 140 cm. - Couleur : Gris. - Poids : 60 kg. - Fonctions : Convertible en lit, rangement intégré.',
                'image' => 'images/produits/furniture_05.jpg',
                'category_id' => 3,
            ],
            [
                'nomProd' => 'Chambre à coucher avec tiroir Noir',
                'prix' => 210000,
                'stock' => 'En stock',
                'description' => 'Cette chambre à coucher noire avec tiroir est une solution élégante et fonctionnelle pour optimiser l\'espace de rangement dans votre chambre. Son design moderne et minimaliste s\'intègre facilement dans tous les styles de décoration.',
                'info' => 'Matériau : MDF et métal. - Dimensions : Lit : 160 cm x 200 cm. ; Table de chevet : 50 cm x 40 cm x 45 cm. ; Armoire : 180 cm x 60 cm x 220 cm. - Couleur : Noir. - Fonctions : Tiroirs de rangement sous le lit, armoire avec étagères et penderie.',
                'image' => 'images/produits/furniture_06.jpg',
                'category_id' => 3,
            ],
            [
                'nomProd' => 'Lampe de table gris LJUSAS YSBY',
                'prix' => 65000,
                'stock' => 'En stock',
                'description' => 'La lampe de table gris LJUSAS YSBY apporte une ambiance chaleureuse et accueillante à votre espace. Son design simple et élégant convient parfaitement à votre salon, chambre ou bureau.',
                'info' => 'Matériau : Métal et tissu. - Dimensions : Hauteur 45 cm, diamètre 25 cm. - Type d\'ampoule : E14 (non incluse). - Couleur : Gris. - Interrupteur : Interrupteur à bascule sur le cordon.',
                'image' => 'images/produits/furniture_07.jpg',
                'category_id' => 3,
            ],
            [
                'nomProd' => 'Coiffeuse pour chambre à coucher avec miroir',
                'prix' => 135000,
                'stock' => 'En stock',
                'description' => 'Cette coiffeuse pour chambre à coucher avec miroir est un meuble élégant et fonctionnel. Idéal pour se préparer, elle offre également un espace de rangement pratique pour vos produits de beauté et accessoires.',
                'info' => 'Matériau : MDF et verre. - Dimensions : 120 cm x 50 cm x 140 cm. - Couleur : Blanc. - Fonctions : Miroir pivotant, tiroirs de rangement. - Assemblage : Facile à assembler, instructions incluses.',
                'image' => 'images/produits/furniture_08.jpg',
                'category_id' => 3,
            ],
            [
                'nomProd' => 'Chaise en faux cuir rouge pour salon',
                'prix' => 55000,
                'stock' => 'En stock',
                'description' => 'Apportez une touche de couleur à votre salon avec cette chaise en faux cuir rouge. Son design moderne et son rembourrage confortable en font un choix idéal pour se détendre ou accueillir des invités.',
                'info' => 'Matériau : Faux cuir et métal. - Dimensions : Hauteur 90 cm, largeur 50 cm, profondeur 60 cm. - Couleur : Rouge. - Poids : 8 kg. - Capacité de charge : 130 kg.',
                'image' => 'images/produits/furniture_09.jpg',
                'category_id' => 3,
            ],
            [
                'nomProd' => 'Doctor Who - Figurine Monsieur Patate',
                'prix' => 4000,
                'stock' => 'En stock',
                'description' => 'La figurine Monsieur Patate Doctor Who est un jouet amusant et éducatif pour les fans de la célèbre série. Ce jouet permet de recréer des scènes emblématiques et d\'imaginer de nouvelles aventures avec votre personnage préféré.',
                'info' => 'Matériau : Plastique durable. - Dimensions : 15 cm de hauteur. - Âge recommandé : 3 ans et plus. - Fonctions : Pièces interchangeables. - Entretien : Facile à nettoyer avec un chiffon humide.',
                'image' => 'images/produits/kidtoy_01.jpg',
                'category_id' => 4,
            ],
            [
                'nomProd' => 'Jouet en bois coloré vert pour bébé',
                'prix' => 3500,
                'stock' => 'En stock',
                'description' => 'Ce jouet en bois coloré en vert pour bébé est parfait pour stimuler la créativité et la motricité fine des tout-petits. Fabriqué à partir de matériaux écologiques, il est sûr et durable.',
                'info' => 'Matériau : Bois naturel, peinture non toxique. - Dimensions : 10 cm x 10 cm x 5 cm. - Âge recommandé : 1 an et plus. - Couleur : Vert. - Sécurité : Conforme aux normes de sécurité EN71.',
                'image' => 'images/produits/kidtoy_02.jpg',
                'category_id' => 4,
            ],
            [
                'nomProd' => 'Voiturette enfant Pat Patrouille',
                'prix' => 7000,
                'stock' => 'En stock',
                'description' => 'La voiturette enfant Pat Patrouille est idéale pour les jeunes fans de la série. Avec ses couleurs vives et son design inspiré des personnages, elle offre des heures de jeu et d\'aventures.',
                'info' => 'Matériau : Plastique robuste. - Dimensions : 50 cm x 30 cm x 25 cm. - Âge recommandé : 2 ans et plus. - Fonctions : Roues fonctionnelles, siège confortable. - Sécurité : Poignée de sécurité pour les parents.',
                'image' => 'images/produits/kidtoy_03.jpg',
                'category_id' => 4,
            ],
            [
                'nomProd' => 'Peluche canard pour bébé',
                'prix' => 4000,
                'stock' => 'En stock',
                'description' => 'Cette peluche bébé canard douce et câline est le compagnon idéal pour les tout-petits. Fabriquée avec des matériaux de haute qualité, elle est parfaite pour les câlins et les jeux.',
                'info' => 'Matériau : Tissu en peluche douce. - Dimensions : 20 cm de hauteur. - Âge recommandé : Dès la naissance. - Entretien : Lavable en machine. - Sécurité : Conforme aux normes de sécurité EN71.',
                'image' => 'images/produits/kidtoy_04.jpg',
                'category_id' => 4,
            ],
            [
                'nomProd' => 'Jouet porteur Ver de terre vert',
                'prix' => 8500,
                'stock' => 'En stock',
                'description' => 'Le jouet porteur Ver de terre vert est parfait pour développer la coordination et la motricité des jeunes enfants. Son design amusant et ses roues stables en font un choix sûr et divertissant.',
                'info' => 'Matériau : Plastique solide. - Dimensions : 60 cm x 25 cm x 30 cm. - Âge recommandé : 18 mois et plus. - Fonctions : Siège confortable, roues faciles à manœuvrer. - Entretien : Facile à nettoyer avec un chiffon humide.',
                'image' => 'images/produits/kidtoy_05.jpg',
                'category_id' => 4,
            ],
            [
                'nomProd' => 'Peluche pour enfants Monstre violet',
                'prix' => 4500,
                'stock' => 'En stock',
                'description' => 'La peluche Monstre violet est un compagnon de jeu fantastique pour les enfants. Avec son design amusant et sa texture douce, elle stimule l\'imagination et offre des moments de câlins inoubliables.',
                'info' => 'Matériau : Tissu en peluche douce. - Dimensions : 25 cm de hauteur. - Âge recommandé : 3 ans et plus. - Entretien : Lavable en machine. - Sécurité : Conforme aux normes de sécurité EN71.',
                'image' => 'images/produits/kidtoy_06.jpg',
                'category_id' => 4,
            ],
            [
                'nomProd' => 'Vélo Blaze 12 pouces pour garçon',
                'prix' => 12000,
                'stock' => 'En stock',
                'description' => 'Le vélo Blaze 12 pouces est conçu pour les jeunes garçons qui aiment l\'aventure. Avec ses roues stabilisatrices amovibles et son design robuste, il offre une conduite stable et sécurisée.',
                'info' => 'Matériau : Cadre en acier. - Dimensions : Roues de 12 pouces. - Âge recommandé : 3 à 5 ans. - Fonctions : Roues stabilisatrices amovibles, freins à main. - Couleur : Rouge et noir.',
                'image' => 'images/produits/kidtoy_07.jpg',
                'category_id' => 4,
            ],
            [
                'nomProd' => 'Pistolets et fusils à eau - Lance pompiers',
                'prix' => 11000,
                'stock' => 'En stock',
                'description' => 'Les pistolets et fusils à eau Lance pompiers sont parfaits pour des jeux d\'eau amusants en extérieur. Avec leur design réaliste et leur grande capacité, ils garantissent des heures de jeu rafraîchissant.',
                'info' => 'Matériau : Plastique durable. - Dimensions : Longueur 30 cm. - Âge recommandé : 5 ans et plus. - Capacité : Réservoir de 500 ml. - Sécurité : Conforme aux normes de sécurité EN71.',
                'image' => 'images/produits/kidtoy_08.jpg',
                'category_id' => 4,
            ],
            [
                'nomProd' => 'Hot Wheels Monster Jam Dragon Vehicle - Vert',
                'prix' => 9000,
                'stock' => 'En stock',
                'description' => 'Le véhicule Hot Wheels Monster Jam Dragon est parfait pour les fans de voitures monstres. Avec ses détails réalistes et ses performances impressionnantes, il offre des heures de jeu excitant.',
                'info' => 'Matériau : Plastique et métal. - Dimensions : 1:64 échelle. - Âge recommandé : 3 ans et plus. - Couleur : Vert. - Fonctions : Roues robustes, design réaliste.',
                'image' => 'images/produits/kidtoy_09.jpg',
                'category_id' => 4,
            ],
            [
                'nomProd' => 'Jouet téléphone enfant avec musique',
                'prix' => 8000,
                'stock' => 'En stock',
                'description' => 'Ce jouet téléphone pour enfant avec musiques est idéal pour divertir et éduquer les tout-petits. Avec ses sons amusants et ses lumières colorées, il stimule l\'apprentissage et l\'imagination.',
                'info' => 'Matériau : Plastique. - Dimensions : 15 cm x 7 cm x 3 cm. - Âge recommandé : 12 mois et plus. - Fonctions : Sons et lumières, musique intégrée. - Alimentation : 2 piles AA (incluses).',
                'image' => 'images/produits/kidtoy_10.jpg',
                'category_id' => 4,
            ],
            [
                'nomProd' => 'Huile de jojoba 50ml et crème de visage',
                'prix' => 8000,
                'stock' => 'En stock',
                'description' => 'Ce duo huile de jojoba 50ml et crème de visage est idéal pour une routine de soin naturelle et hydratante. L\'huile de jojoba pénètre rapidement sans laisser de film gras, tandis que la crème de visage apporte une hydratation intense et durable.',
                'info' => 'Huile de jojoba : Matériau : 100\%\ pure huile de jojoba. - Volume : 50 ml. - Utilisation : Appliquer quelques gouttes sur la peau propre, matin et soir. - Propriétés : Hydratante, apaisante, anti-âge.\r\nCrème de visage : Matériau : Ingrédients naturels. - Volume : 50 ml. - Utilisation : Appliquer sur le visage et le cou matin et soir. - Propriétés : Hydratante, nourrissante, anti-âge.',
                'image' => 'images/produits/organics_spa_1.jpg',
                'category_id' => 5,
            ],
            [
                'nomProd' => 'Savon à la lavande, flocons d\'avoine et amande',
                'prix' => 5000,
                'stock' => 'En stock',
                'description' => 'Le savon lavande, flocons d\'avoine et amande est un produit de soin artisanal qui nettoie en douceur tout en exfoliant délicatement la peau. Il laisse un parfum apaisant de lavande et nourrit la peau grâce aux bienfaits de l\'amande et des flocons d\'avoine.',
                'info' => 'Matériau : Ingrédients naturels (huile de lavande, flocons d\'avoine, huile d\'amande). - Poids : 100 g. - Utilisation : Utiliser quotidiennement pour le visage et le corps. - Propriétés : Exfoliante, hydratante, apaisante.',
                'image' => 'images/produits/organics_spa_3.jpg',
                'category_id' => 5,
            ],
            [
                'nomProd' => 'Gommage exfoliant au sel - soins de la peau et du visage',
                'prix' => 6000,
                'stock' => 'En stock',
                'description' => 'Le gommage exfoliant au sel est parfait pour revitaliser et lisser la peau. Enrichi en minéraux, il élimine les cellules mortes et laisse la peau douce et éclatante. Idéal pour une utilisation régulière sur le visage et le corps.',
                'info' => 'Matériau : Sel marin, huiles essentielles. - Volume : 200 ml. - Utilisation : Appliquer sur la peau humide en mouvements circulaires, puis rincer. - Propriétés : Exfoliante, revitalisante, hydratante.',
                'image' => 'images/produits/organics_spa_4.jpg',
                'category_id' => 5,
            ],
            [
                'nomProd' => 'Crème solaire anti-huile 50 ml Lotion',
                'prix' => 8000,
                'stock' => 'En stock',
                'description' => 'La crème solaire anti-huile 50 ml offre une protection UV efficace tout en laissant la peau sans brillance. Formulée pour les peaux mixtes à grasses, elle protège contre les rayons UVA et UVB sans obstruer les pores.',
                'info' => 'Volume : 50 ml. - SPF : 50+. - Utilisation : Appliquer généreusement avant l\'exposition au soleil, renouveler toutes les 2 heures. - Propriétés : Non-comédogène, résistante à l\'eau, matifiante.',
                'image' => 'images/produits/organics_spa_5.jpg',
                'category_id' => 5,
            ],
            [
                'nomProd' => 'Lotion pour le corps Huile d\'argan et lavande',
                'prix' => 7000,
                'stock' => 'En stock',
                'description' => 'Cette lotion pour le corps à l\'huile d\'argan et lavande hydrate intensément et apaise la peau. Sa texture légère pénètre rapidement, laissant la peau douce, lisse et légèrement parfumée.',
                'info' => 'Matériau : Huile d\'argan, huile essentielle de lavande. - Volume : 250 ml. - Utilisation : Appliquer quotidiennement sur l\'ensemble du corps. - Propriétés : Hydratante, apaisante, nourrissante.',
                'image' => 'images/produits/organics_spa_6.jpg',
                'category_id' => 5,
            ],
            [
                'nomProd' => 'Lait de corps Luxury 250 ml',
                'prix' => 7500,
                'stock' => 'En stock',
                'description' => 'Le lait de corps Luxury 250 ml est une crème hydratante riche qui nourrit et revitalise la peau. Sa formule luxueuse laisse la peau douce et satinée, avec un parfum subtil et élégant.',
                'info' => 'Volume : 250 ml. - Utilisation : Appliquer sur une peau propre et sèche, idéalement après la douche. - Propriétés : Hydratante, adoucissante, revitalisante.',
                'image' => 'images/produits/organics_spa_7.jpg',
                'category_id' => 5,
            ],
            [
                'nomProd' => 'Bougies à l\'avocat avec serviette offerte',
                'prix' => 5500,
                'stock' => 'En stock',
                'description' => 'Ces bougies à l\'avocat sont parfaites pour créer une ambiance relaxante et chaleureuse. Elles sont fabriquées à partir d\'ingrédients naturels et sont livrées avec une serviette douce en cadeau, idéales pour une soirée spa à domicile.',
                'info' => 'Matériau : Cire naturelle à l\'avocat. - Dimensions : 10 cm de hauteur. - Durée de combustion : Jusqu\'à 40 heures. - Couleur : Vert. - Serviette : Coton doux, 30 cm x 30 cm.',
                'image' => 'images/produits/organics_spa_8.jpg',
                'category_id' => 5,
            ],
            [
                'nomProd' => 'Perceuse à percussion 18V LXT',
                'prix' => 68000,
                'stock' => 'En stock',
                'description' => 'La perceuse à percussion 18V LXT est un outil puissant et polyvalent conçu pour les travaux de perçage et de vissage les plus exigeants. Elle offre une performance exceptionnelle grâce à son moteur sans balais et à sa technologie de batterie avancée.',
                'info' => 'Tension : 18V. - Type de moteur : Sans balais. - Vitesse : 0-500 / 0-2,000 tr/min. - Couple : 70 Nm. - Fonctions : Perçage, vissage, percussion. - Accessoires inclus : Batterie, chargeur, coffret de transport.',
                'image' => 'images/produits/tools_equipment_1.jpg',
                'category_id' => 6,
            ],
            [
                'nomProd' => 'Scie à béton 14\" à essence avec lame',
                'prix' => 17000,
                'stock' => 'En stock',
                'description' => 'Cette scie à béton 14\" à essence est idéale pour les travaux de coupe intensifs. Dotée d\'un moteur puissant et d\'une lame de haute qualité, elle offre des coupes précises et efficaces sur le béton et d\'autres matériaux de construction.',
                'info' => 'Diamètre de la lame : 14 pouces. - Type de moteur : Essence. - Puissance : 3.2 kW. - Profondeur de coupe : Jusqu\'à 125 mm. - Fonctions : Coupe humide et sèche. - Accessoires inclus : Lame diamantée.',
                'image' => 'images/produits/tools_equipment_2.jpg',
                'category_id' => 6,
            ],
            [
                'nomProd' => 'Souffleur Stihl BR 600',
                'prix' => 23500,
                'stock' => 'En stock',
                'description' => 'Le souffleur Stihl BR 600 est un outil puissant et ergonomique, parfait pour le nettoyage des grandes surfaces. Avec son moteur performant et son design confortable, il permet de déplacer rapidement les feuilles et les débris.',
                'info' => 'Type de moteur : 4-MIX Stihl. - Puissance : 3.8 CV. - Volume d\'air : 1150 m³/h. - Vitesse de l\'air : 90 m/s. - Poids : 9.8 kg. - Fonctions : Démarrage facile, harnais de confort.',
                'image' => 'images/produits/tools_equipment_3.jpg',
                'category_id' => 6,
            ],
            [
                'nomProd' => 'Compresseur d\'air portable Honda 6.5 HP',
                'prix' => 33000,
                'stock' => 'En stock',
                'description' => 'Le compresseur d\'air portable Honda 6.5 HP est conçu pour une utilisation professionnelle et domestique. Son moteur Honda fiable et sa portabilité en font un outil indispensable pour une variété de tâches pneumatiques.',
                'info' => 'Type de moteur : Honda GX200. - Puissance : 6.5 HP. - Capacité du réservoir : 20 litres. - Débit d\'air : 250 L/min. - Poids : 35 kg. - Fonctions : Portatif, facile à transporter.',
                'image' => 'images/produits/tools_equipment_4.jpg',
                'category_id' => 6,
            ],
            [
                'nomProd' => 'Scie circulaire sans fil avec batterie 20V',
                'prix' => 44000,
                'stock' => 'En stock',
                'description' => 'Cette scie circulaire sans fil avec batterie 20V offre une coupe précise et puissante. Idéale pour les travaux de menuiserie, elle est légère et facile à manier grâce à son design ergonomique.',
                'info' => 'Tension : 20V. - Diamètre de la lame : 6-1/2 pouces. - Vitesse : 5000 tr/min. - Profondeur de coupe : Jusqu\'à 55 mm. - Accessoires inclus : Batterie, chargeur, guide de coupe.',
                'image' => 'images/produits/tools_equipment_5.jpg',
                'category_id' => 6,
            ],
            [
                'nomProd' => 'Perceuse visseuse sans fil DeWalt',
                'prix' => 22000,
                'stock' => 'En stock',
                'description' => 'La perceuse visseuse sans fil DeWalt est un outil essentiel pour tout bricoleur ou professionnel. Avec son moteur puissant et ses deux vitesses, elle facilite les travaux de perçage et de vissage dans divers matériaux.',
                'info' => 'Tension : 18V. - Type de moteur : Sans balais. - Vitesse : 0-450 / 0-1,500 tr/min. - Couple : 60 Nm. - Fonctions : Perçage, vissage. - Accessoires inclus : Batterie, chargeur, coffret de transport.',
                'image' => 'images/produits/tools_equipment_6.jpg',
                'category_id' => 6,
            ],
            [
                'nomProd' => 'Scie circulaire DeWalt 20V 6-1/2 pouces',
                'prix' => 29000,
                'stock' => 'En stock',
                'description' => 'La scie circulaire DeWalt 20V est un outil de haute performance conçu pour les coupes précises. Avec sa lame de 6-1/2 pouces et son moteur puissant, elle est idéale pour les travaux de menuiserie et de construction.',
                'info' => 'Tension : 20V. - Diamètre de la lame : 6-1/2 pouces. - Vitesse : 5150 tr/min. - Profondeur de coupe : Jusqu\'à 65 mm. - Accessoires inclus : Batterie, chargeur, guide de coupe.',
                'image' => 'images/produits/tools_equipment_7.jpg',
                'category_id' => 6,
            ],
            [
                'nomProd' => 'Marteau rotatif DeWalt DC212 N',
                'prix' => 32000,
                'stock' => 'En stock',
                'description' => 'Le marteau rotatif DeWalt DC212 N est conçu pour les travaux de perçage et de burinage dans le béton et la maçonnerie. Avec son moteur puissant et ses fonctions polyvalentes, il est indispensable pour les professionnels de la construction.',
                'info' => 'Tension : 18V. - Type de moteur : Sans balais. - Vitesse : 0-1,100 tr/min. - Force de frappe : 1.9 J. - Fonctions : Perçage, burinage. - Accessoires inclus : Poignée auxiliaire, coffret de transport.',
                'image' => 'images/produits/tools_equipment_8.jpg',
                'category_id' => 6,
            ],
        ]);
    }
}
